# YAML -*- mode: yaml; tab-width: 2; indent-tabs-mode: nil; coding: utf-8 -*-
---
name: check

on:  # yamllint disable-line rule:truthy
  pull_request:
  push:

jobs:
  check:
    runs-on: ubuntu-24.04

    steps:
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: check
        run: make check
